hide_cursor = true
ignore_empty_input = true
immediate_render = true

image {
    monitor = DP-1
    path = ~/wallpaper/1920x1080-87623-retrowave-abstract-artist-artwork-digital-art-hd-4k-behance-minimalism-minimalist.jpgx
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 160
    rounding = -1
    position = 0, 40
    halign = center
    valign = center
}