-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0B03",
  mode = "1920x1200@480.00",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:HGC CR240DM",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company C27F390 HCPTA13602",
  mode = "1920x1080@60.00",
  position = "3840x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "DP-1" })
hl.workspace_rule({ workspace = "2", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1" })
